apiVersion: v1
kind: Secret
metadata:
  name: vsphere-credentials
stringData:
  username: user
  password: pass

---

apiVersion: sources.knative.dev/v1alpha1
kind: VSphereSource
metadata:
  name: blah
spec:
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display

  address: "https://vcsim.default.svc.cluster.local"
  skipTLSVerify: true
  secretRef:
    name: vsphere-credentials

---

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display@sha256:526fdb25f5c26d25506e88e86f22b122b5d56be7de31091bcb1a46e5e8e50615
