apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: to-sockeye
spec:
  filter:
    attributes:
      type: com.vmware.vsphere.VmCreatedEvent
    # attributes:
    #   type: dev.mattmoor.vsample
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: sockeye
---



# apiVersion: sources.knative.dev/v1alpha1
# kind: VSphereBinding
# metadata:
#   name: blah
# spec:
#   subject:
#     apiVersion: serving.knative.dev/v1
#     kind: Service
#     name: sockeye

#   address: vcsim.default.svc.cluster.local
#   skipTLSVerify: true
#   secretRef:
#     name: vsphere-credentials
