apiVersion: batch/v1
kind: Job
metadata:
  generateName: vcsim-setup-tags-
  labels:
    vcsim: setup
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - name: create-category
        image: ko://github.com/mattmoor/vmware-sources/vendor/github.com/vmware/govmomi/govc
        args: ["tags.category.create", "testing"]
      containers:
      - name: create-tag
        image: ko://github.com/mattmoor/vmware-sources/vendor/github.com/vmware/govmomi/govc
        args: ["tags.create", "-c", "testing", "shrug"]
